//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolecularMassCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MolecularMassCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,H,Hydrogen,1.00794
        ///2,He,Helium,4.002602
        ///3,Li,Lithium,6.941
        ///4,Be,Beryllium,9.012182
        ///5,B,Boron,10.811
        ///6,C,Carbon,12.0107
        ///7,N,Nitrogen,14.0067
        ///8,O,Oxygen,15.9994
        ///9,F,Fluorine,18.9984032
        ///10,Ne,Neon,20.1797
        ///11,Na,Sodium,22.98976928
        ///12,Mg,Magnesium,24.305
        ///13,Al,Aluminum,26.9815386
        ///14,Si,Silicon,28.0855
        ///15,P,Phosphorus,30.973762
        ///16,S,Sulfur,32.065
        ///17,Cl,Chlorine,35.453
        ///18,Ar,Argon,39.948
        ///19,K,Potassium,39.0983
        ///20,Ca,Calcium,40.078
        ///21,Sc,Scandium,44.955912
        ///22,Ti,Titanium,47.867
        ///23,V,Vanadium [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PeriodicTable {
            get {
                return ResourceManager.GetString("PeriodicTable", resourceCulture);
            }
        }
    }
}
